### ISSUE TITLE
ValueError: 2949225 is not a valid SimpleMoveStates

### ISSUE THREAD

**Issue by Tombraider720** [WAZAAAAA0/TekkenBot#24]
I'm on the latest version, and I've installed on my C: drive, but I get this error when I get into practice mode.

` Fight detected. Updating gamestate.
Exception in Tkinter callback
ValueError: 2949225 is not a valid SimpleMoveStates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tkinter\__init__.py", line 749, in callit
  File "GUI_TekkenBotPrime.py", line 212, in update_launcher
  File "_FrameDataLauncher.py", line 13, in Update
  File "TekkenGameState.py", line 562, in Update
  File "TekkenGameState.py", line 271, in GetUpdatedState
  File "TekkenGameState.py", line 333, in Bake
  File "c:\program files\python37\lib\enum.py", line 309, in __call__
  File "c:\program files\python37\lib\enum.py", line 561, in __new__
  File "c:\program files\python37\lib\enum.py", line 545, in __new__
  File "c:\program files\python37\lib\enum.py", line 574, in _missing_
ValueError: 2949225 is not a valid SimpleMoveStates `

**Comment by compsyguy** [comment]
That sounds like your memory_address ini file isn't correct. Are you running on a non-hacked version?
